name: Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate snake SVG
      uses: platane/snk@v3
      with:
        github_user: 'preeti-singh'  # Your GitHub username
        svg_out: 'github-contribution-grid-snake.svg'

        png_out: 'github-contribution-grid-snake.png'  # Optional PNG output
        color_snake: '#5f1f70'  # Customize snake color (optional)
        color_grid: '#ffffff'  # Customize grid color (optional)

    - name: Commit and push if there are changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add github-contribution-grid-snake.svg
        git commit -m "Update contribution snake" || echo "No changes to commit"
        git push
